name: Unit Tests (Ubuntu)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * *

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenBLAS
        run: |
          sudo apt-get install libopenblas-dev

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install PyTorch
        run: |
          python -m pip install --upgrade pip
          pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          echo LIBTORCH_PATH=$(python -c "import torch as _; print(_.__path__[0])") >> $GITHUB_ENV

      - name: Install LIBXSMM
        run: |
          git clone https://github.com/libxsmm/libxsmm.git
          cd libxsmm
          make BLAS=0 -j
          cd ..
          echo LIBXSMM_PATH=$(pwd)/libxsmm >> $GITHUB_ENV

      - name: Install einsum_ir
        run: |
          sudo apt-get install scons
          git clone https://github.com/scalable-analyses/einsum_ir.git
          cd einsum_ir
          wget https://github.com/catchorg/Catch2/releases/download/v2.13.10/catch.hpp
          echo "using libxsmm path: ${LIBXSMM_PATH}"
          echo "using libtorch path: ${LIBTORCH_PATH}"
          scons mode=debug+san libtorch=${LIBTORCH_PATH} libxsmm=${LIBXSMM_PATH} blas=yes
          cd ..

      - name: Run unit tests
        run: |
          ./einsum_ir/build/tests